var myFullName;
console.log(myFullName);
console.log(".............................................................................");
myFullName="Renuka Balki";
console.log(myFullName);
console.log(".............................................................................");
myFullName="Renuka Pramod Balki";
console.log(".............................................................................");
console.log(myFullName);
console.log(".............................................................................");
var myLove="I Love JS";
console.log(myLove);
console.log(".............................................................................");
var firstName="Renuka";
console.log(firstName);
console.log(".............................................................................");
var lastName="Balki"
console.log(lastName);
console.log(".............................................................................");
var age="22";
console.log(age);
console.log(".............................................................................");
var address="Pune";
console.log(address);
console.log(".............................................................................");
var pincode="41111";
console.log(pincode);
console.log(".............................................................................");
var gender="Female";
console.log(gender);
console.log(".............................................................................");
var isMarried="false";
console.log(isMarried);